# Generated by Django 2.2.6 on 2019-11-25 19:14

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=finance.models.get_cash_amount, editable=False)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
            ],
            options={
                'verbose_name': 'Средства',
                'verbose_name_plural': 'Средства',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.SmallIntegerField(choices=[(0, 'income'), (1, 'outcome')], default=0)),
                ('amount', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кассовый ордер',
                'verbose_name_plural': 'Кассовые ордера',
            },
        ),
    ]
