# Generated by Django 2.2.6 on 2019-11-17 20:55

from django.db import migrations, models
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='amount',
            field=models.FloatField(default=finance.models.get_cash_amount, editable=False),
        ),
    ]
