# Generated by Django 2.2.6 on 2019-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20191117_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
