# Generated by Django 2.2.6 on 2019-12-03 19:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('sum_acquire', models.FloatField(default=0.0, verbose_name='Закупочная себестоимость')),
                ('years_to_use', models.FloatField(default=1.0, verbose_name='Время эксплуатации (лет)')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Код')),
                ('date_acquire', models.DateField(auto_now_add=True, verbose_name='Дата поступления')),
            ],
            options={
                'verbose_name': 'Еденица актива',
                'verbose_name_plural': 'Еденицы активов',
            },
        ),
        migrations.CreateModel(
            name='AssetItemSupplyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total_price', models.FloatField(default=0.0, verbose_name='Общая стоимость')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
            ],
            options={
                'verbose_name': 'Заказ активов',
                'verbose_name_plural': 'Заказы активов',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип актива',
                'verbose_name_plural': 'Типы активов',
            },
        ),
        migrations.CreateModel(
            name='SupportReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отчет по ремонту',
                'verbose_name_plural': 'Отчеты по ремонту',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_planned', models.DateTimeField(verbose_name='Запланированное время')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ремонтные работы',
                'verbose_name_plural': 'Ремонтные работы',
            },
        ),
        migrations.CreateModel(
            name='SupportTicketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ордер на материалы',
                'verbose_name_plural': 'Ордеры на материалы',
            },
        ),
    ]
