# Generated by Django 2.2.6 on 2019-12-03 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketitem',
            name='material_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.UsageOrder', verbose_name='Ордер на материалы'),
        ),
        migrations.AddField(
            model_name='supportticketitem',
            name='support_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket_items', to='assets.SupportTicket', verbose_name='Ремонтные работы'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='asset_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='assets.AssetItem', verbose_name='Еденица актива'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Departament', verbose_name='Ответственный департамент'),
        ),
        migrations.AddField(
            model_name='supportreport',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='supportreport',
            name='support_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SupportTicket', verbose_name='Ремонтные работы'),
        ),
        migrations.AddField(
            model_name='assetitemsupplyorder',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_supply_orders', to='assets.Asset', verbose_name='Актив'),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_items', to='assets.Asset', verbose_name='Актив'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetType', verbose_name='Тип актива'),
        ),
    ]
