# Generated by Django 2.2.6 on 2019-11-14 20:57

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Группа актива', 'verbose_name_plural': 'Группы активов'},
        ),
        migrations.AddField(
            model_name='assetitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='respondent',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='respondent',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
