# Generated by Django 2.2.6 on 2019-11-25 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('material', '0001_initial'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketitem',
            name='material_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.UsageOrder'),
        ),
        migrations.AddField(
            model_name='supportticketitem',
            name='support_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket_items', to='assets.SupportTicket'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='asset_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='assets.AssetItem'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='respondent',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportreport',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportreport',
            name='support_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.SupportTicket'),
        ),
        migrations.AddField(
            model_name='assetitemsupplyorder',
            name='ticket',
            field=models.ForeignKey(limit_choices_to={'ticket_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='asset_item_supply_orders', to='finance.Ticket'),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Asset'),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='supply_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_item', to='assets.AssetItemSupplyOrder'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetType'),
        ),
    ]
