# Generated by Django 2.2.6 on 2019-11-16 21:47

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20191114_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Актив', 'verbose_name_plural': 'Активы'},
        ),
        migrations.AlterModelOptions(
            name='assetitem',
            options={'verbose_name': 'Еденица актива', 'verbose_name_plural': 'Еденицы активов'},
        ),
        migrations.AlterModelOptions(
            name='supportticketitem',
            options={'verbose_name': 'Ордер на материалы', 'verbose_name_plural': 'Ордеры на материалы'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='info',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='assettype',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
