# Generated by Django 2.2.6 on 2019-12-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20191203_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='sum_acquire',
        ),
        migrations.AddField(
            model_name='assetitem',
            name='sum_acquire',
            field=models.FloatField(default=0.0, verbose_name='Закупочная себестоимость'),
        ),
    ]
