# Generated by Django 2.2.6 on 2019-11-16 21:59

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20191116_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='info',
            field=picklefield.fields.PickledObjectField(blank=True, default=dict, editable=False, null=True),
        ),
    ]
