# Generated by Django 2.2.6 on 2019-11-17 18:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20191116_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
