# Generated by Django 2.2.6 on 2019-11-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20191117_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='asset_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.AssetItem'),
            preserve_default=False,
        ),
    ]
