# Generated by Django 2.2.6 on 2019-11-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_supportticket_asset_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='asset_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='assets.AssetItem'),
        ),
    ]
