# Generated by Django 2.2.6 on 2019-11-17 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20191117_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticketitem',
            name='support_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_ticket_items', to='assets.SupportTicket'),
        ),
    ]
