# Generated by Django 2.2.6 on 2019-11-19 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20191118_2356'),
        ('assets', '0008_auto_20191117_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItemSupplyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in', models.PositiveIntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_item_supply_orders', to='finance.Ticket')),
            ],
            options={
                'verbose_name': 'Заказ активов',
                'verbose_name_plural': 'Заказы активов',
            },
        ),
        migrations.AddField(
            model_name='assetitem',
            name='supply_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_item', to='assets.AssetItemSupplyOrder'),
            preserve_default=False,
        ),
    ]
