# Generated by Django 2.2.6 on 2019-11-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_remove_assetitem_sum_acquire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitemsupplyorder',
            name='ticket',
            field=models.ForeignKey(limit_choices_to={'ticket_type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='asset_item_supply_orders', to='finance.Ticket'),
        ),
    ]
