# Generated by Django 2.2.6 on 2019-11-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20191119_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetitem',
            name='name',
        ),
    ]
