# Generated by Django 2.2.6 on 2019-11-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_remove_assetitem_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetitem',
            name='uuid',
            field=models.UUIDField(default='35907124d2e1451c8bea10c5acf76654', editable=False),
        ),
    ]
