# Generated by Django 2.2.6 on 2019-11-19 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assetitem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
