# Generated by Django 2.2.6 on 2019-11-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseAsset',
        ),
    ]
