# Generated by Django 2.2.6 on 2019-11-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_financialasset_immaterialasset_martialassetsupport_materialasset_materialassetorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialasset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='immaterialasset',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MartialAssetSupport',
        ),
        migrations.RemoveField(
            model_name='materialasset',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='MaterialAssetOrder',
        ),
        migrations.DeleteModel(
            name='FinancialAsset',
        ),
        migrations.DeleteModel(
            name='ImmaterialAsset',
        ),
        migrations.DeleteModel(
            name='MaterialAsset',
        ),
    ]
