# Generated by Django 2.2.6 on 2019-12-03 19:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Код')),
                ('name', models.CharField(max_length=512, verbose_name='Наименовние')),
                ('price', models.FloatField(default=0.0, verbose_name='Закупочная себестоимость')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Дополнительные характеристики')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категрии',
            },
        ),
        migrations.CreateModel(
            name='UsageOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_out', models.FloatField(default=0.0, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время выдачи')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Выдача',
                'verbose_name_plural': 'Выдачи',
            },
        ),
        migrations.CreateModel(
            name='SupplyOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_in', models.FloatField(default=0.0, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время поступления')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='material.Material', verbose_name='Материал')),
                ('responsive_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Заявка на снабжение',
                'verbose_name_plural': 'Заявки на снабжение',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.MaterialCategory', verbose_name='Категория'),
        ),
    ]
