# Generated by Django 2.2.6 on 2019-11-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_remove_usageorder_responsive_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplyorder',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_orders', to='material.Material'),
        ),
    ]
